import { useEffect, useState } from 'react';
import { ArrowLeft, ExternalLink } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import type { Restaurant } from '@turku-lunch/shared';
import Header from '../components/Header';
import { api } from '../services/api';
import { euro, updated } from '../utils/format';

export default function RestaurantPage() {
  const { slug = '' } = useParams();
  const [r,setR]=useState<Restaurant|null>(null); const [error,setError]=useState<string|null>(null);
  useEffect(()=>{api.restaurant(slug).then(setR).catch((e:Error)=>setError(e.message));},[slug]);
  return <><Header/><main className="mx-auto max-w-4xl p-4"><Link className="btn mb-4" to="/"><ArrowLeft size={16}/>Takaisin kartalle</Link>{error&&<div className="card p-4">{error}</div>}{!r&&!error&&<div className="card p-6">Ladataan…</div>}{r&&<div className="space-y-4"><section className="card p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-bold">{r.name}</h1><p className="mt-1 text-slate-500">{r.address}</p></div><div className="text-right"><div className="text-2xl font-bold">{euro(r.studentPrice)}</div><div className="text-xs text-slate-500">opiskelijalounas</div></div></div><div className="mt-5 flex flex-wrap gap-2"><span className="badge">{r.studentMealType}</span>{r.premiumStudentPrice!=null&&<span className="badge">Premium {euro(r.premiumStudentPrice)}</span>}{r.veganAvailable&&<span className="badge">Vegaani</span>}{r.glutenFreeAvailable&&<span className="badge">Gluteeniton</span>}</div></section><section className="card p-6"><h2 className="text-lg font-semibold">Tänään</h2><div className="mt-3 space-y-3">{r.todayMenu?.meals.map((m,i)=><div key={i} className="border-b border-slate-100 pb-3 last:border-0 dark:border-slate-800"><div className="text-xs uppercase tracking-wide text-slate-500">{m.category}</div><div className="font-medium">{m.name}</div><div className="mt-1 flex flex-wrap gap-1">{m.diets.map(d=><span className="badge" key={d}>{d}</span>)}</div></div>)}{!r.todayMenu?.meals.length&&<p className="text-slate-500">Ruokalistaa ei saatavilla.</p>}</div></section><section className="card p-6 text-sm"><h2 className="font-semibold">Tiedot ja lähteet</h2><dl className="mt-3 grid gap-2 sm:grid-cols-2"><div><dt className="text-slate-500">Lounasaika</dt><dd>{r.lunchHours||'Ei tietoa'}</dd></div><div><dt className="text-slate-500">Päivitetty</dt><dd>{updated(r.todayMenu?.fetchedAt)}</dd></div></dl><div className="mt-4 flex flex-wrap gap-2"><a className="btn border" href={r.websiteUrl} target="_blank" rel="noreferrer">Ravintolan sivu <ExternalLink size={14}/></a><a className="btn border" href={r.menuUrl} target="_blank" rel="noreferrer">Ruokalistan lähde <ExternalLink size={14}/></a></div></section></div>}</main></>;
}
